### ISSUE TITLE
Cross platform build (specifically for Windows 10 with VS 2017 or 2019)

### ISSUE THREAD

**Issue by carun** [Terabee/terabee_api#3]
We can't build terabee_api on Windows at the moment. This needs to be fixed.

**Comment by pptaszni** [comment]
For now we do not support building this API for Windows. Marked this as feature request. Our engineers will prioritize this task with respect to the current situation. In the meantime you might consider submitting a PR.

**Comment by carun** [comment]
Thanks. We bought 20+ devices and want to work with it on Windows. Appreciate your help.

**Comment by carun** [comment]
@pptaszni any thoughts on when we can expect Windows support? Thanks.

**Comment by pptaszni** [comment]
@MarcinPilch , @pl-kabaradjian , please provide some estimation

**Comment by pl-kabaradjian** [comment]
Hello @carun 
I invite you to contact our support team [here](https://www.terabee.com/contact/), so we can better address your use case.

Cheers,

**Comment by carun** [comment]
@pl-kabaradjian Thanks, I contacted support team a month ago with no response till now. I will try again. Is there a support email ID that we can connect with?

**Comment by pl-kabaradjian** [comment]
> @pl-kabaradjian Thanks, I contacted support team a month ago with no response till now. I will try again. Is there a support email ID that we can connect with?

You should have received an email from our support when you submitted a ticket. You can reply to that email directly to ping our support again.

Cheers,

**Comment by carun** [comment]
>You should have received an email from our support when you submitted a ticket.

I didn't receive any email earlier. I submitted a ticket again today and I didn't receive now as well. There's no email in my spam folder, neither on the remote server. FYI, both the tickets were submitted by this email: `arun dot chandrasekaran at necam dot com`. @pl-kabaradjian

**Comment by carun** [comment]
The only notification I see is this
![image](https://user-images.githubusercontent.com/471374/87187251-b925b200-c2a1-11ea-9baf-0d82b0b9d608.png)

**Comment by JLAsensio** [comment]
Please send an email to this email address: 
jose.asensio@terabee.com

**Comment by carun** [comment]
Thanks @JLAsensio I've sent an email yesterday, but I didn't receive any acknowledgement about the email receipt. Hope someone looked at the email.

**Comment by JLAsensio** [comment]
We have created a customer ticket for you. You can use that ticket to communicate with us. 
Apologies for our delay in our answer. Yesterday was the French National Day and that's why we could not answer you.
